version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    container_name: auth-service
    restart: unless-stopped
    networks:
      - rbac-network

  role-service:
    build: ./role-service
    ports:
      - "4000:4000"
    container_name: role-service
    restart: unless-stopped
    networks:
      - rbac-network

  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    container_name: user-service
    restart: unless-stopped
    networks:
      - rbac-network

networks:
  rbac-network:
    driver: bridge
